### ISSUE TITLE
[Vue warn]: Property or method "handleComplete" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. 

### ISSUE THREAD

**Issue by acrobat22** [guillaumebriday/vue-scroll-progressbar#24]
Hello,
I start in vue.js
I do not understand everything yet :-(
I installed your plugin and I have this error.
I don't understand where this error comes from.
Can you help me ?
Thank you

**Comment by guillaumebriday** [comment]
I think you copied this line: 

```html
<vue-scroll-progress-bar @complete="handleComplete" height="2rem" />
```

If so you need to define a method `handleComplete` or remove the `@complete="handleComplete"`

Is it good ?

**Comment by acrobat22** [comment]
I deleted @complete = "handleComplete" and effectively I no longer have the warning and the progress bar is working properly.

Thank you.

**Comment by guillaumebriday** [comment]
Great!
