### ISSUE TITLE
ie 11 problem

### ISSUE THREAD

**Issue by Firat-Bayram** [guillaumebriday/vue-scroll-progressbar#33]
![Untitled](https://user-images.githubusercontent.com/6624079/80315393-0399a580-8800-11ea-8e60-4c2d889e03bd.png)
![Untitled2](https://user-images.githubusercontent.com/6624079/80315407-1613df00-8800-11ea-9942-fc9291f4be68.png)

**Comment by guillaumebriday** [comment]
Hey, IE 11 is not maintained anymore.

If you really need to support it, you need to find a fix or another library I'm sorry.
