### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by ZeffK** [guillaumebriday/vue-scroll-progressbar#38]
![issu](https://user-images.githubusercontent.com/54438151/82151377-0163bd80-9879-11ea-8d5e-3a3aa28345ae.png)

**Comment by guillaumebriday** [comment]
Can you show me some code? Or send me sandbox link?

**Comment by ZeffK** [comment]
Solved !
mounted the component in instance 
new Vue({
  render: h => h(App),
}).$mount('#app')
