### ISSUE TITLE
Add Debounce?

### ISSUE THREAD

**Issue by pmochine** [guillaumebriday/vue-scroll-progressbar#39]
I'm just wondering. Why don't you use debounce for scrolling? It's just too much if you are firing the calculation for each small scrolling?

Here is one video as an example: https://scotch.io/courses/getting-started-with-javascript-for-web-development/scroll-progress

**Comment by guillaumebriday** [comment]
Hey! Didn't implement that for that project yet.

Maybe this package will do the job https://github.com/component/debounce

Would you consider to open a PR?

thanks

**Comment by guillaumebriday** [comment]
Or with Lodash directly https://www.npmjs.com/package/lodash.debounce

**Comment by pmochine** [comment]
Hmmmm. I'm actually not that sure anymore if we want to debounce. Maybe throttling is better?

Have to think about it.

But if you compare it here https://css-tricks.com/the-difference-between-throttling-and-debouncing/

Throttle makes more sense. Have to play around with it.

**Comment by guillaumebriday** [comment]
Ok debounce is not appropriate here, I went with Throttle

Thanks for the issue, will release tonight
