### ISSUE TITLE
Improve performance with passive

### ISSUE THREAD

**Issue by pmochine** [guillaumebriday/vue-scroll-progressbar#40]
Another thing that I notice. You could use ` { passive: true }` for the addEventListener for scroll.
This improves performance!

Here for example https://stackoverflow.com/questions/37721782/what-are-passive-event-listeners

Here is the code if the browser supports passive:

```
let supportsPassive = false;
try {
    const opts = Object.defineProperty({}, 'passive', {
        // eslint-disable-next-line
        get() {
            supportsPassive = true;
        },
    });

    window.addEventListener('testPassive', null, opts);
    window.removeEventListener('testPassive', null, opts);
} catch (e) {
    // nothing
}
```

and then for example:

`window.addEventListener('scroll', _.debounce(this.calculatesomething, 50), supportsPassive ? { passive: true } : false);`

**Comment by guillaumebriday** [comment]
Great! Will definitely do that

I prefer the Mozilla approach though https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners

thanks 🙏

**Comment by pmochine** [comment]
Yeah even better! Greetings to Lyon! My favourite city in France!

**Comment by pmochine** [comment]
@guillaumebriday is it possible to update the package to npm? It's still from November 2019

**Comment by guillaumebriday** [comment]
@pmochine done
