### ISSUE TITLE
Component not rendering correctly on production build

### ISSUE THREAD

**Issue by maikbeeldr** [guillaumebriday/vue-scroll-progressbar#52]
Hi Gaillaume,

Thank you for your plugin. It's working great on my Nuxt 2 website in development mode, but I am encountering difficulties in production mode. I've just added a question on Stackoverflow, since I am not entirely sure if the problem lies in my Nuxt installation or the package itself. 

https://stackoverflow.com/questions/77805521/component-output-renders-incorrectly-after-running-nuxt-production-build

I am at a loss here, hoping you can point me to the right direction for a solution. I can share the production URL with you if you like. 

<img width="1231" alt="Screenshot 2024-01-12 at 10 16 24" src="https://github.com/guillaumebriday/vue-scroll-progress-bar/assets/77977778/0e55f630-73bd-4f37-a8d7-97de2f0792c6">
<img width="1192" alt="Screenshot 2024-01-12 at 10 14 03" src="https://github.com/guillaumebriday/vue-scroll-progress-bar/assets/77977778/1802b35d-d729-4689-93dc-b87aa6ac034b">

**Comment by guillaumebriday** [comment]
Did you try to disable SSR?

**Comment by maikbeeldr** [comment]
On the plugin or on the Nuxt install? My site is a headless server side rendered website.

**Comment by kissu** [comment]
You could wrap the component into a [`client-only`](https://v2.nuxt.com/docs/features/nuxt-components#the-client-only-component) since it doesn't add a lot of value for SEO anyway.
Forcing your whole Nuxt app to be SEO-only is quite a big constraint.

**Comment by maikbeeldr** [comment]
Thanks @kissu, that did the trick!

**Comment by kissu** [comment]
I guess we can mark this as completed. 👍🏻
